name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Build the Docker image
        run: module add docker
      - name: a Build the Docker image
        run: nohup dockerd-rootless.sh > /dev/null >/dev/null 2>&1 &
      - name: run a build
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest    
    
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
     
#     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
